server:
  port: 9000
spring:
  application:
    name: rabbit-provide
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.206.229.175:3306/provide?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cache:
    type: redis
  redis:
    host: 123.206.229.175
    port: 6379
    timeout: 10000ms
    database: 12
    jedis:
      pool:
         max-active: 8
         max-idle: 8
         min-idle: 0
         max-wait: -1ms
  rabbitmq:
     host: 123.206.229.175
     port: 5672
     username: admin
     password: admin

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.rabbit.mq.rabbit.provide.entity